import "server-only";
import { Type, type Schema } from "@google/genai";
import { z } from "zod";
import { geminiClient, MODEL, parseJson } from "./client";
import type { FormMetricsPayload } from "@/lib/form/metrics";

// Spec §10.3, verbatim.
const SYSTEM_PROMPT = `You write short, specific coaching notes from movement analysis data.
Two to four sentences. Second person. Name the single most important fix
first. Do not list every fault. Do not be effusive.

You are reading joint-angle data from one camera. You cannot see spinal
position, bracing, or breathing. Do not comment on what the data does not
cover. If overall_score is above 85, say the movement looked solid and
give one refinement rather than manufacturing a problem.

End with one concrete instruction for the next set.

Return ONLY valid JSON matching the schema.`;

const FormSummaryResponseSchema = z.object({ summary: z.string() });
const RESPONSE_SCHEMA: Schema = {
  type: Type.OBJECT,
  properties: { summary: { type: Type.STRING } },
  required: ["summary"],
};

// Appended in code, never generated by the model — spec §7's honesty
// requirement, verbatim.
const CLOSING_DISCLAIMER =
  "This is a movement-pattern check, not a medical or coaching assessment. If something hurts, stop and see a professional.";

export async function generateFormSummary(metrics: FormMetricsPayload): Promise<string> {
  const client = geminiClient();
  const response = await client.models.generateContent({
    model: MODEL,
    contents: `Input: ${JSON.stringify({
      exercise: metrics.exercise,
      camera_view: metrics.cameraView,
      rep_count: metrics.repCount,
      overall_score: metrics.overallScore,
      rep_metrics: metrics.repMetrics,
      faults: metrics.faults,
    })}`,
    config: {
      systemInstruction: SYSTEM_PROMPT,
      responseMimeType: "application/json",
      responseSchema: RESPONSE_SCHEMA,
    },
  });
  const { summary } = parseJson(FormSummaryResponseSchema, response.text, "form summary");
  return `${summary.trim()} ${CLOSING_DISCLAIMER}`;
}
