// Generated by the Supabase MCP (generate_typescript_types) against project
// dfrcnbmgtgntllsahdgg. Regenerate after every migration batch; do not hand-edit.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      ai_jobs: {
        Row: {
          created_at: string
          error: string | null
          id: string
          kind: Database["public"]["Enums"]["job_kind"]
          latency_ms: number | null
          model: string | null
          status: Database["public"]["Enums"]["job_status"]
          tokens_in: number | null
          tokens_out: number | null
          user_id: string
        }
        Insert: {
          created_at?: string
          error?: string | null
          id?: string
          kind: Database["public"]["Enums"]["job_kind"]
          latency_ms?: number | null
          model?: string | null
          status: Database["public"]["Enums"]["job_status"]
          tokens_in?: number | null
          tokens_out?: number | null
          user_id: string
        }
        Update: {
          created_at?: string
          error?: string | null
          id?: string
          kind?: Database["public"]["Enums"]["job_kind"]
          latency_ms?: number | null
          model?: string | null
          status?: Database["public"]["Enums"]["job_status"]
          tokens_in?: number | null
          tokens_out?: number | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_jobs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      body_metrics: {
        Row: {
          body_fat_pct: number | null
          id: string
          note: string | null
          recorded_on: string
          user_id: string
          waist_cm: number | null
          weight_kg: number | null
        }
        Insert: {
          body_fat_pct?: number | null
          id?: string
          note?: string | null
          recorded_on: string
          user_id: string
          waist_cm?: number | null
          weight_kg?: number | null
        }
        Update: {
          body_fat_pct?: number | null
          id?: string
          note?: string | null
          recorded_on?: string
          user_id?: string
          waist_cm?: number | null
          weight_kg?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "body_metrics_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      exercises: {
        Row: {
          cues: string[]
          demo_url: string | null
          equipment: Database["public"]["Enums"]["equipment_kind"]
          form_camera_view: string | null
          form_primary_angle: string | null
          form_rules: Json | null
          id: string
          is_unilateral: boolean
          load_increment_kg: number
          movement_pattern: string | null
          name: string
          primary_muscle: string
          secondary_muscles: string[]
          slug: string
        }
        Insert: {
          cues?: string[]
          demo_url?: string | null
          equipment: Database["public"]["Enums"]["equipment_kind"]
          form_camera_view?: string | null
          form_primary_angle?: string | null
          form_rules?: Json | null
          id?: string
          is_unilateral?: boolean
          load_increment_kg?: number
          movement_pattern?: string | null
          name: string
          primary_muscle: string
          secondary_muscles?: string[]
          slug: string
        }
        Update: {
          cues?: string[]
          demo_url?: string | null
          equipment?: Database["public"]["Enums"]["equipment_kind"]
          form_camera_view?: string | null
          form_primary_angle?: string | null
          form_rules?: Json | null
          id?: string
          is_unilateral?: boolean
          load_increment_kg?: number
          movement_pattern?: string | null
          name?: string
          primary_muscle?: string
          secondary_muscles?: string[]
          slug?: string
        }
        Relationships: []
      }
      form_analyses: {
        Row: {
          camera_view: string | null
          coach_summary: string | null
          exercise_id: string
          faults: Json
          frames_saved: boolean
          id: string
          overall_score: number | null
          recorded_at: string
          rep_count: number
          rep_metrics: Json
          session_id: string | null
          user_id: string
        }
        Insert: {
          camera_view?: string | null
          coach_summary?: string | null
          exercise_id: string
          faults: Json
          frames_saved?: boolean
          id?: string
          overall_score?: number | null
          recorded_at?: string
          rep_count: number
          rep_metrics: Json
          session_id?: string | null
          user_id: string
        }
        Update: {
          camera_view?: string | null
          coach_summary?: string | null
          exercise_id?: string
          faults?: Json
          frames_saved?: boolean
          id?: string
          overall_score?: number | null
          recorded_at?: string
          rep_count?: number
          rep_metrics?: Json
          session_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "form_analyses_exercise_id_fkey"
            columns: ["exercise_id"]
            isOneToOne: false
            referencedRelation: "exercises"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "form_analyses_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "workout_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "form_analyses_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      habit_logs: {
        Row: {
          habit_id: string
          id: string
          log_date: string
          source: string
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          habit_id: string
          id?: string
          log_date: string
          source?: string
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          habit_id?: string
          id?: string
          log_date?: string
          source?: string
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "habit_logs_habit_id_fkey"
            columns: ["habit_id"]
            isOneToOne: false
            referencedRelation: "habits"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "habit_logs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      habits: {
        Row: {
          archived_at: string | null
          auto_source: string | null
          cadence: Database["public"]["Enums"]["habit_cadence"]
          color_token: string
          emoji: string | null
          id: string
          name: string
          reminder_time: string | null
          rest_day_enabled: boolean
          rest_day_weekday: number | null
          sort_index: number
          target_per_week: number
          user_id: string
        }
        Insert: {
          archived_at?: string | null
          auto_source?: string | null
          cadence?: Database["public"]["Enums"]["habit_cadence"]
          color_token?: string
          emoji?: string | null
          id?: string
          name: string
          reminder_time?: string | null
          rest_day_enabled?: boolean
          rest_day_weekday?: number | null
          sort_index?: number
          target_per_week?: number
          user_id: string
        }
        Update: {
          archived_at?: string | null
          auto_source?: string | null
          cadence?: Database["public"]["Enums"]["habit_cadence"]
          color_token?: string
          emoji?: string | null
          id?: string
          name?: string
          reminder_time?: string | null
          rest_day_enabled?: boolean
          rest_day_weekday?: number | null
          sort_index?: number
          target_per_week?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "habits_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      meal_favorites: {
        Row: {
          created_at: string
          id: string
          items: Json
          name: string
          source_meal_id: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          items: Json
          name: string
          source_meal_id?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          items?: Json
          name?: string
          source_meal_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "meal_favorites_source_meal_id_fkey"
            columns: ["source_meal_id"]
            isOneToOne: false
            referencedRelation: "meals"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "meal_favorites_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      meal_items: {
        Row: {
          carbs_g: number
          confidence: number | null
          fat_g: number
          fiber_g: number
          grams: number | null
          id: string
          kcal: number
          kcal_high: number | null
          kcal_low: number | null
          meal_id: string
          name: string
          order_index: number
          portion_description: string | null
          protein_g: number
          user_edited: boolean
        }
        Insert: {
          carbs_g?: number
          confidence?: number | null
          fat_g?: number
          fiber_g?: number
          grams?: number | null
          id?: string
          kcal: number
          kcal_high?: number | null
          kcal_low?: number | null
          meal_id: string
          name: string
          order_index?: number
          portion_description?: string | null
          protein_g?: number
          user_edited?: boolean
        }
        Update: {
          carbs_g?: number
          confidence?: number | null
          fat_g?: number
          fiber_g?: number
          grams?: number | null
          id?: string
          kcal?: number
          kcal_high?: number | null
          kcal_low?: number | null
          meal_id?: string
          name?: string
          order_index?: number
          portion_description?: string | null
          protein_g?: number
          user_edited?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "meal_items_meal_id_fkey"
            columns: ["meal_id"]
            isOneToOne: false
            referencedRelation: "meals"
            referencedColumns: ["id"]
          },
        ]
      }
      meals: {
        Row: {
          created_at: string
          eaten_at: string
          id: string
          image_path: string | null
          meal_type: string | null
          note: string | null
          source: string
          status: Database["public"]["Enums"]["meal_status"]
          user_id: string
        }
        Insert: {
          created_at?: string
          eaten_at?: string
          id?: string
          image_path?: string | null
          meal_type?: string | null
          note?: string | null
          source: string
          status?: Database["public"]["Enums"]["meal_status"]
          user_id: string
        }
        Update: {
          created_at?: string
          eaten_at?: string
          id?: string
          image_path?: string | null
          meal_type?: string | null
          note?: string | null
          source?: string
          status?: Database["public"]["Enums"]["meal_status"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "meals_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      nutrition_targets: {
        Row: {
          carbs_g: number
          created_at: string
          effective_from: string
          fat_g: number
          id: string
          kcal: number
          method: string | null
          protein_g: number
          rationale: string | null
          user_id: string
        }
        Insert: {
          carbs_g: number
          created_at?: string
          effective_from: string
          fat_g: number
          id?: string
          kcal: number
          method?: string | null
          protein_g: number
          rationale?: string | null
          user_id: string
        }
        Update: {
          carbs_g?: number
          created_at?: string
          effective_from?: string
          fat_g?: number
          id?: string
          kcal?: number
          method?: string | null
          protein_g?: number
          rationale?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "nutrition_targets_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      planned_sets: {
        Row: {
          exercise_id: string
          id: string
          is_warmup: boolean
          order_index: number
          origin: string
          planned_workout_id: string
          rest_seconds: number
          set_number: number
          target_load_kg: number | null
          target_reps_high: number
          target_reps_low: number
          target_rpe: number | null
          user_id: string
        }
        Insert: {
          exercise_id: string
          id?: string
          is_warmup?: boolean
          order_index: number
          origin?: string
          planned_workout_id: string
          rest_seconds?: number
          set_number: number
          target_load_kg?: number | null
          target_reps_high: number
          target_reps_low: number
          target_rpe?: number | null
          user_id: string
        }
        Update: {
          exercise_id?: string
          id?: string
          is_warmup?: boolean
          order_index?: number
          origin?: string
          planned_workout_id?: string
          rest_seconds?: number
          set_number?: number
          target_load_kg?: number | null
          target_reps_high?: number
          target_reps_low?: number
          target_rpe?: number | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "planned_sets_exercise_id_fkey"
            columns: ["exercise_id"]
            isOneToOne: false
            referencedRelation: "exercises"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "planned_sets_planned_workout_id_fkey"
            columns: ["planned_workout_id"]
            isOneToOne: false
            referencedRelation: "planned_workouts"
            referencedColumns: ["id"]
          },
        ]
      }
      planned_workouts: {
        Row: {
          day_index: number
          estimated_minutes: number | null
          id: string
          name: string
          program_week_id: string
          user_id: string
        }
        Insert: {
          day_index: number
          estimated_minutes?: number | null
          id?: string
          name: string
          program_week_id: string
          user_id: string
        }
        Update: {
          day_index?: number
          estimated_minutes?: number | null
          id?: string
          name?: string
          program_week_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "planned_workouts_program_week_id_fkey"
            columns: ["program_week_id"]
            isOneToOne: false
            referencedRelation: "program_weeks"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          activity_level: Database["public"]["Enums"]["activity_level"] | null
          created_at: string
          date_of_birth: string | null
          days_per_week: number | null
          display_name: string | null
          equipment: Json
          experience_level:
            | Database["public"]["Enums"]["experience_level"]
            | null
          goal: Database["public"]["Enums"]["goal_type"] | null
          height_cm: number | null
          hide_energy: boolean
          id: string
          limitations: string | null
          onboarded_at: string | null
          session_minutes: number | null
          sex: Database["public"]["Enums"]["sex"] | null
          timezone: string
          unit_system: Database["public"]["Enums"]["unit_system"]
        }
        Insert: {
          activity_level?: Database["public"]["Enums"]["activity_level"] | null
          created_at?: string
          date_of_birth?: string | null
          days_per_week?: number | null
          display_name?: string | null
          equipment?: Json
          experience_level?:
            | Database["public"]["Enums"]["experience_level"]
            | null
          goal?: Database["public"]["Enums"]["goal_type"] | null
          height_cm?: number | null
          hide_energy?: boolean
          id: string
          limitations?: string | null
          onboarded_at?: string | null
          session_minutes?: number | null
          sex?: Database["public"]["Enums"]["sex"] | null
          timezone?: string
          unit_system?: Database["public"]["Enums"]["unit_system"]
        }
        Update: {
          activity_level?: Database["public"]["Enums"]["activity_level"] | null
          created_at?: string
          date_of_birth?: string | null
          days_per_week?: number | null
          display_name?: string | null
          equipment?: Json
          experience_level?:
            | Database["public"]["Enums"]["experience_level"]
            | null
          goal?: Database["public"]["Enums"]["goal_type"] | null
          height_cm?: number | null
          hide_energy?: boolean
          id?: string
          limitations?: string | null
          onboarded_at?: string | null
          session_minutes?: number | null
          sex?: Database["public"]["Enums"]["sex"] | null
          timezone?: string
          unit_system?: Database["public"]["Enums"]["unit_system"]
        }
        Relationships: []
      }
      program_weeks: {
        Row: {
          deload_reason: string | null
          id: string
          is_deload: boolean
          program_id: string
          user_id: string
          week_number: number
        }
        Insert: {
          deload_reason?: string | null
          id?: string
          is_deload?: boolean
          program_id: string
          user_id: string
          week_number: number
        }
        Update: {
          deload_reason?: string | null
          id?: string
          is_deload?: boolean
          program_id?: string
          user_id?: string
          week_number?: number
        }
        Relationships: [
          {
            foreignKeyName: "program_weeks_program_id_fkey"
            columns: ["program_id"]
            isOneToOne: false
            referencedRelation: "programs"
            referencedColumns: ["id"]
          },
        ]
      }
      programs: {
        Row: {
          created_at: string
          days_per_week: number | null
          generation_input: Json | null
          generation_input_hash: string | null
          goal: string | null
          id: string
          name: string
          split: string | null
          status: string
          total_weeks: number
          user_id: string
        }
        Insert: {
          created_at?: string
          days_per_week?: number | null
          generation_input?: Json | null
          generation_input_hash?: string | null
          goal?: string | null
          id?: string
          name: string
          split?: string | null
          status?: string
          total_weeks?: number
          user_id: string
        }
        Update: {
          created_at?: string
          days_per_week?: number | null
          generation_input?: Json | null
          generation_input_hash?: string | null
          goal?: string | null
          id?: string
          name?: string
          split?: string | null
          status?: string
          total_weeks?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "programs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      progression_runs: {
        Row: {
          applied_set_ids: string[]
          id: string
          input: Json
          output: Json
          ran_at: string
          session_id: string
          superseded_by: string | null
          user_id: string
        }
        Insert: {
          applied_set_ids?: string[]
          id?: string
          input: Json
          output: Json
          ran_at?: string
          session_id: string
          superseded_by?: string | null
          user_id: string
        }
        Update: {
          applied_set_ids?: string[]
          id?: string
          input?: Json
          output?: Json
          ran_at?: string
          session_id?: string
          superseded_by?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "progression_runs_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: true
            referencedRelation: "workout_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "progression_runs_superseded_by_fkey"
            columns: ["superseded_by"]
            isOneToOne: false
            referencedRelation: "progression_runs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "progression_runs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      set_logs: {
        Row: {
          completed_at: string
          e1rm: number | null
          e1rm_trusted: boolean | null
          exercise_id: string
          id: string
          is_warmup: boolean
          load_kg: number
          reps: number
          rpe: number | null
          session_id: string
          set_number: number
        }
        Insert: {
          completed_at?: string
          e1rm?: number | null
          e1rm_trusted?: boolean | null
          exercise_id: string
          id?: string
          is_warmup?: boolean
          load_kg: number
          reps: number
          rpe?: number | null
          session_id: string
          set_number: number
        }
        Update: {
          completed_at?: string
          e1rm?: number | null
          e1rm_trusted?: boolean | null
          exercise_id?: string
          id?: string
          is_warmup?: boolean
          load_kg?: number
          reps?: number
          rpe?: number | null
          session_id?: string
          set_number?: number
        }
        Relationships: [
          {
            foreignKeyName: "set_logs_exercise_id_fkey"
            columns: ["exercise_id"]
            isOneToOne: false
            referencedRelation: "exercises"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "set_logs_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "workout_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      workout_sessions: {
        Row: {
          ended_at: string | null
          id: string
          note: string | null
          planned_workout_id: string | null
          session_rpe: number | null
          started_at: string
          user_id: string
        }
        Insert: {
          ended_at?: string | null
          id?: string
          note?: string | null
          planned_workout_id?: string | null
          session_rpe?: number | null
          started_at?: string
          user_id: string
        }
        Update: {
          ended_at?: string | null
          id?: string
          note?: string | null
          planned_workout_id?: string | null
          session_rpe?: number | null
          started_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "workout_sessions_planned_workout_id_fkey"
            columns: ["planned_workout_id"]
            isOneToOne: false
            referencedRelation: "planned_workouts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "workout_sessions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      check_daily_cap: {
        Args: {
          p_kind: Database["public"]["Enums"]["job_kind"]
          p_limit: number
        }
        Returns: boolean
      }
      delete_account: { Args: never; Returns: undefined }
      export_account: { Args: never; Returns: Json }
    }
    Enums: {
      activity_level: "sedentary" | "light" | "moderate" | "high" | "athlete"
      equipment_kind:
        | "barbell"
        | "dumbbell"
        | "machine"
        | "cable"
        | "bodyweight"
        | "bands"
      experience_level: "beginner" | "intermediate" | "advanced"
      goal_type:
        | "fat_loss"
        | "muscle_gain"
        | "strength"
        | "endurance"
        | "general_health"
      habit_cadence: "daily" | "weekly"
      job_kind:
        | "meal_vision"
        | "program_gen"
        | "form_summary"
        | "weekly_checkin"
      job_status: "pending" | "succeeded" | "failed" | "fallback"
      meal_status: "processing" | "ready" | "failed" | "manual"
      sex: "male" | "female" | "unspecified"
      unit_system: "metric" | "imperial"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      activity_level: ["sedentary", "light", "moderate", "high", "athlete"],
      equipment_kind: [
        "barbell",
        "dumbbell",
        "machine",
        "cable",
        "bodyweight",
        "bands",
      ],
      experience_level: ["beginner", "intermediate", "advanced"],
      goal_type: [
        "fat_loss",
        "muscle_gain",
        "strength",
        "endurance",
        "general_health",
      ],
      habit_cadence: ["daily", "weekly"],
      job_kind: [
        "meal_vision",
        "program_gen",
        "form_summary",
        "weekly_checkin",
      ],
      job_status: ["pending", "succeeded", "failed", "fallback"],
      meal_status: ["processing", "ready", "failed", "manual"],
      sex: ["male", "female", "unspecified"],
      unit_system: ["metric", "imperial"],
    },
  },
} as const
